kind: ConfigMap
apiVersion: v1
metadata:
  name: cmm-cpp-maintenance-task
  namespace: cmm-uat
  uid: 0c887899-0a65-4037-89fb-042456134482
  resourceVersion: '103990971'
  creationTimestamp: '2022-09-27T14:09:00Z'
  labels:
    app.kubernetes.io/instance: cmm-uat
    velero.io/backup-name: migration-2fc5e-initial-f5gtx
    velero.io/restore-name: migration-2fc5e-final-vdscp
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","data":{"application.yaml":"spring:\n 
      application:\n    name: cmm-cpp-maintenance-task\n\n  cloud:\n   
      task:\n      closecontext_enabled: true\n      name:
      ${spring.application.name}\n\n  mail:\n    host:
      smtpinternal.wellpoint.com\n\ndatasource:\n  service: false\n  task:
      true\n\n#Information on the Service\ninfo:\n  app:\n   name:
      cmm-cpp-maintenance-task\n   description: cmm-cpp-maintenance-task\n  
      version: 1.0.0\ndatasource:\n  service: false\n  task:
      true"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"cmm-uat"},"name":"cmm-cpp-maintenance-task","namespace":"cmm-uat"}}
  managedFields:
    - manager: velero-server
      operation: Update
      apiVersion: v1
      time: '2022-09-27T14:09:00Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:application.yaml': {}
        'f:metadata':
          'f:annotations':
            .: {}
            'f:kubectl.kubernetes.io/last-applied-configuration': {}
          'f:labels':
            .: {}
            'f:app.kubernetes.io/instance': {}
            'f:velero.io/backup-name': {}
            'f:velero.io/restore-name': {}
data:
  application.yaml: |-
    spring:
      application:
        name: cmm-cpp-maintenance-task

      cloud:
        task:
          closecontext_enabled: true
          name: ${spring.application.name}

      mail:
        host: smtpinternal.wellpoint.com

    #Information on the Service
    info:
      app:
       name: cmm-cpp-maintenance-task
       description: cmm-cpp-maintenance-task
       version: 1.0.0
    datasource:
      service: false
      task: true
