kind: ConfigMap
apiVersion: v1
metadata:
  name: cmm-cpp-cfnp-task
  namespace: cmm-uat
  uid: 2d7e1472-c7d3-4253-a262-513e421fd8d0
  resourceVersion: '103990933'
  creationTimestamp: '2022-09-27T14:08:59Z'
  labels:
    app.kubernetes.io/instance: cmm-uat
    velero.io/backup-name: migration-2fc5e-initial-f5gtx
    velero.io/restore-name: migration-2fc5e-final-vdscp
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","data":{"application.yaml":"spring:\n 
      application:\n    name: cmm-cpp-cfnp-task\n\n  cloud:\n    task:\n     
      closecontext_enabled: true\n      name: ${spring.application.name}\n\n 
      mail:\n    host: smtpinternal.wellpoint.com\n\n#Information on the
      Service\ninfo:\n  app:\n   name: cmm-cpp-cfnp-task\n   description:
      cmm-cpp-cfnp-task\n   version: 1.0.0\ndatasource:\n  service: false\n 
      task:
      true"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"cmm-uat"},"name":"cmm-cpp-cfnp-task","namespace":"cmm-uat"}}
  managedFields:
    - manager: velero-server
      operation: Update
      apiVersion: v1
      time: '2022-09-27T14:08:59Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:application.yaml': {}
        'f:metadata':
          'f:annotations':
            .: {}
            'f:kubectl.kubernetes.io/last-applied-configuration': {}
          'f:labels':
            .: {}
            'f:app.kubernetes.io/instance': {}
            'f:velero.io/backup-name': {}
            'f:velero.io/restore-name': {}
data:
  application.yaml: |-
    spring:
      application:
        name: cmm-cpp-cfnp-task

      cloud:
        task:
          closecontext_enabled: true
          name: ${spring.application.name}

      mail:
        host: smtpinternal.wellpoint.com

    #Information on the Service
    info:
      app:
       name: cmm-cpp-cfnp-task
       description: cmm-cpp-cfnp-task
       version: 1.0.0
    datasource:
      service: false
      task: true
