kind: ConfigMap
apiVersion: v1
metadata:
  name: cmm-cpp-medicareload-task
  namespace: cmm-uat
  uid: 1afc838e-839b-4aa6-b6cf-2360faac5d14
  resourceVersion: '103990973'
  creationTimestamp: '2022-09-27T14:09:00Z'
  labels:
    app.kubernetes.io/instance: cmm-uat
    velero.io/backup-name: migration-2fc5e-initial-f5gtx
    velero.io/restore-name: migration-2fc5e-final-vdscp
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"v1","data":{"application.yaml":"spring:\n  batch:\n   
      job:\n      enabled: false\n  mail:\n    host:
      smtpinternal.wellpoint.com\ndatasource:\n  service: false\n  task:
      true"},"kind":"ConfigMap","metadata":{"annotations":{},"labels":{"app.kubernetes.io/instance":"cmm-uat"},"name":"cmm-cpp-medicareload-task","namespace":"cmm-uat"}}
  managedFields:
    - manager: velero-server
      operation: Update
      apiVersion: v1
      time: '2022-09-27T14:09:00Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:data':
          .: {}
          'f:application.yaml': {}
        'f:metadata':
          'f:annotations':
            .: {}
            'f:kubectl.kubernetes.io/last-applied-configuration': {}
          'f:labels':
            .: {}
            'f:app.kubernetes.io/instance': {}
            'f:velero.io/backup-name': {}
            'f:velero.io/restore-name': {}
data:
  application.yaml: |-
    spring:
      batch:
        job:
          enabled: false
      mail:
        host: smtpinternal.wellpoint.com
    datasource:
      service: false
      task: true
