kind: ReplicaSet
apiVersion: apps/v1
metadata:
  annotations:
    deployment.kubernetes.io/desired-replicas: '1'
    deployment.kubernetes.io/max-replicas: '2'
    deployment.kubernetes.io/revision: '3'
    openshift.io/backup-registry-hostname: 'image-registry.openshift-image-registry.svc:5000'
    openshift.io/backup-server-version: '1.21'
    openshift.io/restore-registry-hostname: 'image-registry.openshift-image-registry.svc:5000'
    openshift.io/restore-server-version: '1.21'
  resourceVersion: '950931050'
  name: scdf-server-7c7d48d5ff
  uid: 05a7fb20-6882-4dfb-a683-1d089bcb5c71
  creationTimestamp: '2023-09-11T16:24:35Z'
  generation: 3
  managedFields:
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2023-09-23T19:26:37Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:deployment.kubernetes.io/desired-replicas': {}
            'f:deployment.kubernetes.io/max-replicas': {}
            'f:deployment.kubernetes.io/revision': {}
            'f:openshift.io/backup-registry-hostname': {}
            'f:openshift.io/backup-server-version': {}
            'f:openshift.io/restore-registry-hostname': {}
            'f:openshift.io/restore-server-version': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:pod-template-hash': {}
          'f:ownerReferences':
            .: {}
            'k:{"uid":"f1bea202-9129-49eb-84f5-f037d5815fc6"}': {}
        'f:spec':
          'f:replicas': {}
          'f:selector': {}
          'f:template':
            'f:metadata':
              'f:labels':
                .: {}
                'f:app': {}
                'f:pod-template-hash': {}
            'f:spec':
              'f:volumes':
                .: {}
                'k:{"name":"cmmnp2"}':
                  .: {}
                  'f:name': {}
                  'f:persistentVolumeClaim':
                    .: {}
                    'f:claimName': {}
                'k:{"name":"ie3np2"}':
                  .: {}
                  'f:name': {}
                  'f:persistentVolumeClaim':
                    .: {}
                    'f:claimName': {}
              'f:containers':
                'k:{"name":"scdf-server"}':
                  'f:image': {}
                  'f:volumeMounts':
                    .: {}
                    'k:{"mountPath":"cmm"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
                    'k:{"mountPath":"ie3"}':
                      .: {}
                      'f:mountPath': {}
                      'f:name': {}
                  'f:terminationMessagePolicy': {}
                  .: {}
                  'f:resources':
                    .: {}
                    'f:limits':
                      .: {}
                      'f:cpu': {}
                      'f:memory': {}
                    'f:requests':
                      .: {}
                      'f:cpu': {}
                      'f:memory': {}
                  'f:env':
                    'k:{"name":"spring.datasource.username"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"KUBERNETES_NAMESPACE"}':
                      .: {}
                      'f:name': {}
                      'f:valueFrom':
                        .: {}
                        'f:fieldRef': {}
                    'k:{"name":"spring.datasource.password"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"TZ"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"SPRING_CLOUD_DATAFLOW_FEATURES_SCHEDULES_ENABLED"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"SPRING_CLOUD_SKIPPER_CLIENT_SERVER_URI"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    .: {}
                    'k:{"name":"spring.datasource.driver-class-name"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"SPRING_CLOUD_CONFIG_ENABLED"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"SPRING_CLOUD_DATAFLOW_TASK_COMPOSEDTASKRUNNER_URI"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"SPRING_CLOUD_DATAFLOW_FEATURES_ANALYTICS_ENABLED"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"spring.datasource.url"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"SPRING_APPLICATION_JSON"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"SPRING_CLOUD_TASK_CLOSECONTEXT_ENABLED"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"SPRING_CLOUD_KUBERNETES_SECRETS_ENABLE_API"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"SPRING_CLOUD_KUBERNETES_CONFIG_NAME"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                    'k:{"name":"SPRING_CLOUD_DATAFLOW_SERVER_URI"}':
                      .: {}
                      'f:name': {}
                      'f:value': {}
                  'f:terminationMessagePath': {}
                  'f:imagePullPolicy': {}
                  'f:ports':
                    .: {}
                    'k:{"containerPort":80,"protocol":"TCP"}':
                      .: {}
                      'f:containerPort': {}
                      'f:protocol': {}
                  'f:name': {}
              'f:dnsPolicy': {}
              'f:serviceAccount': {}
              'f:restartPolicy': {}
              'f:schedulerName': {}
              'f:terminationGracePeriodSeconds': {}
              'f:serviceAccountName': {}
              'f:securityContext': {}
    - manager: kube-controller-manager
      operation: Update
      apiVersion: apps/v1
      time: '2023-09-23T19:26:41Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:availableReplicas': {}
          'f:fullyLabeledReplicas': {}
          'f:observedGeneration': {}
          'f:readyReplicas': {}
          'f:replicas': {}
      subresource: status
  namespace: cmm-uat
  ownerReferences:
    - apiVersion: apps/v1
      kind: Deployment
      name: scdf-server
      uid: f1bea202-9129-49eb-84f5-f037d5815fc6
      controller: true
      blockOwnerDeletion: true
  labels:
    app: scdf-server
    pod-template-hash: 7c7d48d5ff
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scdf-server
      pod-template-hash: 7c7d48d5ff
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: scdf-server
        pod-template-hash: 7c7d48d5ff
    spec:
      restartPolicy: Always
      serviceAccountName: scdf-sa
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      securityContext: {}
      containers:
        - resources:
            limits:
              cpu: '2'
              memory: 12Gi
            requests:
              cpu: '1'
              memory: 4Gi
          terminationMessagePath: /dev/termination-log
          name: scdf-server
          env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: SPRING_CLOUD_CONFIG_ENABLED
              value: 'false'
            - name: TZ
              value: GMT
            - name: SPRING_CLOUD_DATAFLOW_FEATURES_ANALYTICS_ENABLED
              value: 'true'
            - name: SPRING_CLOUD_DATAFLOW_FEATURES_SCHEDULES_ENABLED
              value: 'true'
            - name: SPRING_CLOUD_KUBERNETES_SECRETS_ENABLE_API
              value: 'true'
            - name: SPRING_CLOUD_KUBERNETES_CONFIG_NAME
              value: scdf-server
            - name: SPRING_CLOUD_DATAFLOW_SERVER_URI
              value: 'http://10.91.131.69:9393'
            - name: SPRING_CLOUD_SKIPPER_CLIENT_SERVER_URI
              value: 'http://10.91.245.96:7577/api'
            - name: SPRING_APPLICATION_JSON
              value: >-
                { "maven": { "local-repository": null, "remote-repositories": {
                "repo1": { "url": "https://repo.spring.io/libs-snapshot"} } } }
            - name: spring.datasource.url
              value: 'jdbc:oracle:thin:@dc04dx22-scan1.internal.das:1525/CMMENRL2T'
            - name: spring.datasource.username
              value: E3CORE
            - name: spring.datasource.password
              value: 'E3core2t#123'
            - name: spring.datasource.driver-class-name
              value: oracle.jdbc.driver.OracleDriver
            - name: SPRING_CLOUD_DATAFLOW_TASK_COMPOSEDTASKRUNNER_URI
              value: >-
                docker:image-registry.openshift-image-registry.svc:5000/cmm-uat/cmm-cpp-system-composedtaskrunner-j11:latest
            - name: SPRING_CLOUD_TASK_CLOSECONTEXT_ENABLED
              value: 'true'
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: cmmnp2
              mountPath: cmm
            - name: ie3np2
              mountPath: ie3
          terminationMessagePolicy: File
          image: >-
            image-registry.openshift-image-registry.svc:5000/cmm-uat/cmm-cpp-system-dataflowengine-j11:latest
      serviceAccount: scdf-sa
      volumes:
        - name: cmmnp2
          persistentVolumeClaim:
            claimName: cmmnp2
        - name: ie3np2
          persistentVolumeClaim:
            claimName: ie3np2
      dnsPolicy: ClusterFirst
status:
  replicas: 1
  fullyLabeledReplicas: 1
  readyReplicas: 1
  availableReplicas: 1
  observedGeneration: 3
